name: whatsapp_clone
description: Flutter WhatsApp Clone
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  flutter_riverpod: ^2.3.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  file_picker: ^5.2.6
  image_picker: ^1.0.0
  country_picker: ^2.0.20
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.20
  intl: ^0.18.1
  emoji_picker_flutter: ^1.5.2
  flutter_keyboard_visibility: ^5.4.0
  phone_number: ^2.0.1
  uuid: ^3.0.7
  share_plus: ^7.0.2
  url_launcher: ^6.1.10
  flutter_contacts: ^1.1.6
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  firebase_storage: ^11.2.4
  flutter_emoji: ^2.4.0
  video_player: ^2.7.0
  mime: ^1.0.4
  open_file_plus: ^3.4.1
  logger: ^1.1.0
  flutter_webrtc: ^0.9.35
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_messaging: ^14.6.5
  http: ^0.13.6
  visibility_detector: ^0.4.0+2
  image: ^4.0.17
  audioplayers: ^5.1.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.16
  camera: ^0.10.5+3
  photo_manager: ^2.7.1
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/landing_img.png
    - assets/images/PENDING.png
    - assets/images/SENT.png
    - assets/images/DELIVERED.png
    - assets/images/SEEN.png
    - assets/images/dark/chat_bg.png
    - assets/images/chat_bg.png
    - assets/images/logo.png
    - assets/images/avatar.png

  fonts:
    - family: AzeretMono
      fonts:
        - asset: assets/fonts/AzeretMono-Regular.ttf
